# Generated by Django 5.2.7 on 2025-10-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file',
            new_name='file_path',
        ),
    ]
